### ISSUE TITLE
Add link to nuget package

### ISSUE THREAD

**Issue by LokiMidgard** [Dirkster99/InplaceEditBoxLib#11]
I wasn't sure there is an offical Nuget package. You could add a Link to nuget in your readme.

At least I did not found one using search.

**Comment by Dirkster99** [comment]
I added a link to the Readme although it was there before - you can see it if you click on the downloads badge. I received a similar feedback on the [AvalonDock](https://github.com/Dirkster99/AvalonDock) project so I guess I'll have to add these links to all my projects ...

**Comment by LokiMidgard** [comment]
@Dirkster99 Ah...  
I assumed the download badge would lead me to the Release section. I looked for a nuget badge :)
