### ISSUE TITLE
ParentScrollViewer is null in EditBoxAdorner.MeasureOverride()

### ISSUE THREAD

**Issue by TheColonel2688** [Dirkster99/InplaceEditBoxLib#2]
I have placed an EditBox in a separate usercontrol, that is used inside MainWindow.

Relevant declaration code

```
<WrapPanel Grid.Row="0">
            <Label>Step: </Label>
            <!--<Label Content="{Binding Name}"></Label>-->
            <views1:EditBox Text="{Binding Path=Name, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}"
                            DisplayText="{Binding Path=Name, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}" 
                            RenameCommand="{Binding Path=Step_Rename}"
                            RenameCommandParameter="{Binding}"
                            Focusable="True"
                            VerticalAlignment="Stretch"
                            HorizontalAlignment="Left"
            />
        </WrapPanel>
```

So when I tried an edit with a slow double click. I get a Null reference exception. I enabled 3rd Party Debug and have tracked the object that is null to EditBoxAdorner.MeasureOverride().

Is is the ParentScrolViewer in the line
`controlPosition = _EditBox.ParentScrollViewer.PointToScreen(new Point(0, 0));`

![ben-laptop - 2018-05-11 22-08-55](https://user-images.githubusercontent.com/8753759/39952626-fe50f90a-5568-11e8-9581-6c0457061a9a.png)

**Comment by TheColonel2688** [comment]
Yes if you could create a pre release package that would be great. It might be tonight or tomorrow night before I can test it.

**Comment by Dirkster99** [comment]
OK, I created a new package (actually forgot to check the pre-release check mark because I had to fix a few other things to get this to roll but I am very sure this is working) please confirm whether tihis fixes the problem without loosing functionality.

Thanks Dirk

**Comment by TheColonel2688** [comment]
Dirkster99,

I installed the 1.1.1 nuget package and this fixed my problem. Thank you very much.

The strange thing is that I am not running this on a 4K monitor. My res is 1920x1080 and my scaling is 100%

![image](https://user-images.githubusercontent.com/8753759/40212048-00eea9f2-5a1c-11e8-89da-904848cbe39a.png)
