### ISSUE TITLE
.Net Core 3.0

### ISSUE THREAD

**Issue by virzak** [Dirkster99/InplaceEditBoxLib#4]
Any plans to target multiple frameworks including the upcoming .Net Core 3.0?

**Comment by Dirkster99** [comment]
Hi virzak,

since you brought up the question would you be able to give me some background information (a link or short explaination) towards using .Net Core in this project?

Thanks Dirk

**Comment by virzak** [comment]
Hi Dirk,

That's all very new to everyone. I'll see if I can do a pull request over the weekend, but to summarize, it seems that Microsoft implements all its new APIs into .NET Core, which won't be immediately available in .NET framework. There are daily builds at https://github.com/dotnet/core/blob/master/daily-builds.md

You can run `dotnet new wpf` to create a .net core wpf application.

I'll see if I can make a pull request over the weekend.

**Comment by virzak** [comment]
Looks like before any pull requests, [multitargeting](https://github.com/dotnet/core-sdk/issues/88) needs to be available. Other than that the project converts easily, but having 2 different projects is probably not desirable.

**Comment by Dirkster99** [comment]
OK. I'll have a look at the linked article - it describes how this can be targeted to NetCore 3.0, right? I'll see if I can do it and get back to you when I am done or when there are questions comming up...

**Comment by Dirkster99** [comment]
I was able to convert this but the application hangs on start-up for me - did you get it started and working with NetCore 3.0?

I installed these 2:
- https://github.com/dotnet/core-setup
- https://github.com/dotnet/core-sdk

and converted the project using the command line only, which got me to this:
[InPlaceEditTextBoxLib.zip](https://github.com/Dirkster99/InplaceEditBoxLib/files/2596350/InPlaceEditTextBoxLib.zip)
[InPlaceEditTextBoxLib_Output.txt](https://github.com/Dirkster99/InplaceEditBoxLib/files/2596351/InPlaceEditTextBoxLib_Output.txt)

See *Output.txt for the output I got on compile - so its compiling with 10 warnings but hangs for an eternity until I can actually kill it never mind getting it to run - did you get it to run?

Do you happen to know when multitargeting should be available?

**Comment by Dirkster99** [comment]
I compiled it with "dotnet build" so its happening with .net core - its probably best to install a later daily build and check back to see if it disappears at some point...

**Comment by Dirkster99** [comment]
yes, we are looking at the same problem, which is more likely than not, the fact that .Net Core 3.0 is not final, yet. I guess, the best we can do is come back to this from time to time since filling a bug is to early, right?

**Comment by virzak** [comment]
Sure. At the same time, since the issue is outside of the library, perhaps it is ready for nuget pre-release?

**Comment by Dirkster99** [comment]
![untitled](https://user-images.githubusercontent.com/2129700/51555000-e5176280-1e76-11e9-8030-3443344b3357.png)
done

**Comment by virzak** [comment]
Great, thanks so much!!!

**Comment by Dirkster99** [comment]
Hi Victor,

I worked a little bit more on the [NetCore branch](https://github.com/Dirkster99/InplaceEditBoxLib/tree/NetCoreMutliTargeting/source/InplaceEditBoxLib/Views) with VS 2019 Preview and .NetCore3 Preview 8 today and got the application to load its data as before again. But the `EditBox` control still does not seem to work - the images below can be re-produced when everything thats's `EditBox` in MainWindow.xaml is commented out and the `TextBlock` tag is instead commented in.

You can clearly see that the EditBox control is missing. I searched for quit a while now but cannot find a problem and so I am wondering if this should be reported to the .NetCore project or whether I am overseeing something - what do you think?

The TreeView with TextBlock activated:
![TextBlock](https://user-images.githubusercontent.com/2129700/64069360-6d998500-cc48-11e9-8fd3-56d0e6e0396b.png)

The TreeView with EditBox activated:
![EditInPlaceTextBox](https://user-images.githubusercontent.com/2129700/64069361-6d998500-cc48-11e9-9853-775f7f4eb7fb.png)

**Comment by Dirkster99** [comment]
I simply ported the control project one more time with VS 2019 Preview and NetCore 3 Proeview 8 and got it now working as it should :-) result will be available in nuget/release 1.4.

**Comment by virzak** [comment]
Awesome, glad it worked. Sorry I wasn't able to get to this in time. It is a labor day weekend here :)
