### ISSUE TITLE
log4net dependency

### ISSUE THREAD

**Issue by virzak** [Dirkster99/InplaceEditBoxLib#5]
log4net is missing the nuget package, but is a requirement for the dll to run.
Had to add it to my project even though I have no need for it and use Serilog for my logging

**Comment by Dirkster99** [comment]
Hi,

thanks for the hint - I was not aware of this - thought I'd removed this a long time ago ...

I've removed the reference to log4net in version 1.1.2.1 of the library release and the nuget package should now come without the log4net reference - please let me know if the issue remains for you.

You can either use the Package Manager line to update:
Install-Package Dirkster.InplaceEditBoxLib -Version 1.1.2.1

or wait an hour or so until nuget will supply the update automatically...
