### ISSUE TITLE
Can this be used to edit DataGrid Header?

### ISSUE THREAD

**Issue by ajhalls** [Dirkster99/InplaceEditBoxLib#6]
I need a way to rename column headers and stumbled across this, hoping it can help.

**Comment by Dirkster99** [comment]
Yes, the **RoundWatermarkTextBox** in this sample does something similar:

https://github.com/Dirkster99/YalvLib/blob/master/src/YalvLib/View/YalvView.xaml

The Yalv was created 6 years ago from a diferent author and so I have not been able to implement it with the InplaceEditBoxLib, yet, but I would recommend it these days for sure.

Its probably best if you create a small demo program with a static data source - this would be very helpful if/when you have specific questions - it always helps if you can look at code in such cases ...

**Comment by Dirkster99** [comment]
In 2nd thought I'd go with the Textbox Version because the Text editing area is limited by the column widt which seems Mord natural for this use case
