### ISSUE TITLE
Different text color for selected item than unselected

### ISSUE THREAD

**Issue by Drachenkaetzchen** [Dirkster99/InplaceEditBoxLib#7]
In the following screenshot (as linked in the README) it can be seen that the selected item has a different text color than the rest:

![](https://raw.githubusercontent.com/Dirkster99/InplaceEditBoxLib/master/00_Docu/00_Docu/EditOverlay/Step1.png)

However, upon having a look at the demo project as well as Edi it seems that this is currently not supported or implemented. Can you give an advice if this is possible with the current version?

**Comment by Dirkster99** [comment]
The screensot is from Windows 7 and accent color is slightly different on it. Overall, you should be able to change it as you can see in the dark theme screenshot. Look into the definitions in the `LightBrushs.xaml` and `DarkBrushs.xaml` file. You can ue the resource keys referenced there to change these colors ...

**Comment by Drachenkaetzchen** [comment]
> The screensot is from Windows 7 and accent color is slightly different on it. Overall, you should be able to change it as you can see in the dark theme screenshot. Look into the definitions in the `LightBrushs.xaml` and `DarkBrushs.xaml` file. You can ue the resource keys referenced there to change these colors ...

Nope. There's only one resource key, namely `NormalForegroundKey`. There is no different key for a **selected** item, which needs to be different. As `NormalForegroundKey` is the only key there, I of course changed it to `#FFFFFF`. My selected `TreeViewItem` has a dark purple background, was such the foreground color for a selected item needs to be `#FFFFFF`. Unselected items need to be `#000000`.

Also [ResourceKeys.cs](https://github.com/Dirkster99/InplaceEditBoxLib/blob/7391f3ab34d4646dd0f10ee41d06887f16d925cd/source/InplaceEditBoxLib/Themes/ResourceKeys.cs) lists only a single key for each the Brush and the Color.

**Comment by Dirkster99** [comment]
Ah, yes you are of course right. The selection color depends on the ItemsControl you are using - more to the point, on the theme that you are using to color your ItemsControl that contains the EditBox control.

So, if you use a TreeViewItem to host the EditBox you have to turn to the selection color of the TreeView.

Here is an example based on MLib:
https://github.com/Dirkster99/MLib/blob/master/source/Components/MLib/Controls/TreeView.xaml
You should be able to change the color in line 175 which should change the color of the selected item in the `TreeView`.

You need to locate this in your theming library if you are using a different one or re-template and style your TreeView based on the standard templates and styles.

The [control](https://github.com/Dirkster99/InplaceEditBoxLib/blob/master/source/InplaceEditBoxLib/Views/EditBoxAdorner.cs) is using a `TextBox` when you are actually changing the displayed string so you need to turn to the `TextBox` template and styles for coloring these things.

**Comment by Drachenkaetzchen** [comment]
> Ah, yes you are of course right. The selection color depends on the ItemsControl you are using - more to the point, on the theme that you are using to color your ItemsControl that contains the EditBox control.

Well, prior using `EditBox` my tree was styled correctly.

Code before
```xaml
<HierarchicalDataTemplate
            x:Key="Contents"
            DataType="{x:Type sharedModels1:PresetBank}"
            ItemsSource="{Binding PresetBanks, Converter={StaticResource NodeSorter}}">
            <TextBlock Text="{Binding BankName}" />
</HierarchicalDataTemplate>
```

Code after: 

```xaml
 <HierarchicalDataTemplate
            x:Key="Contents"
            DataType="{x:Type sharedModels1:PresetBank}"
            ItemsSource="{Binding PresetBanks, Converter={StaticResource NodeSorter}}">
            <views:EditBox

                Text="{Binding Path=BankName, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}"

                DisplayText="{Binding BankName, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}"
                Focusable="True"
                RenameCommand="{Binding Data.RenameBankCommand, Source={StaticResource DataContextProxy}}"
                RenameCommandParameter="{Binding}"
                VerticalAlignment="Stretch"

                HorizontalAlignment="Left"
                Margin="2,0" />
            <!--<TextBlock Text="{Binding BankName}" />-->
        </HierarchicalDataTemplate>
```

The problem is that the style for `EditBox` always uses a fixed color brush, which of course comes down to the `DisplayText` property.

The culprit is located in [EditBox.xaml#24](https://github.com/Dirkster99/InplaceEditBoxLib/blob/master/source/InplaceEditBoxLib/Views/EditBox.xaml#L24)

I think this should be a `TemplateBinding` and there should be a style property for `PART_TextBlock` so that there is a chance to actually style the control without having to subclass.

**Comment by Drachenkaetzchen** [comment]
By the way, I decided a few minutes ago that I won't go with inline rename as especially in a TreeView, it's not intuitive to double click with a longer interval to avoid Expand/Collapse and instead implemented a popup rename (which also, in my use case, provides an easier implementation). If you like, you can close the issue, but I bet a solution would be interesting for others ;)

**Comment by Dirkster99** [comment]
... would a change of two lines solve your issue?

```
    <Style TargetType="{x:Type local:EditBox}" >
        <Setter Property="HorizontalAlignment" Value="Left"  />
        <Setter Property="VerticalAlignment"   Value="Center" />
        <Setter Property="Foreground" Value="{DynamicResource {x:Static reskeys:ResourceKeys.NormalForegroundBrushKey}}"/>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type local:EditBox}">
                    <Grid>
                        <TextBlock x:Name="PART_TextBlock" MinWidth="10"
                                   HorizontalAlignment="Left"
                                   VerticalAlignment="Center"
                                   Foreground="{TemplateBinding Foreground}"
                     />

                        <!-- The measurment textblock is never visible it's simply there to tell the length of a string to the textbox
                             but it should have the same font and layout as the visbile textblock and the in place textbox (!)
                        -->
                        <TextBlock x:Name="PART_MeasureTextBlock" MinWidth="10"
                                   HorizontalAlignment="Left"
                                   VerticalAlignment="Center"
                                   Visibility="Hidden"
                                   Foreground="Green"
                                 />
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

```

**Comment by Drachenkaetzchen** [comment]
> ... would a change of two lines solve your issue?
I think so, should I decide later on that I use `InplaceEditBoxLib` again (which is likely) ;)

However, I would recommend to name it `DisplayTextForegroundBrush`, so it's clear what the property does.

**Comment by Dirkster99** [comment]
I have no trouble changing it as you suggest - thanks for the suggestion - this control is rather old and partly refactored from other project which makes you sort of blind 👍

**Comment by Drachenkaetzchen** [comment]
> I have no trouble changing it as you suggest - thanks for the suggestion - this control is rather old and partly refactored from other project which makes you sort of blind 👍

You're welcome and yes - I know that too well :)

**Comment by Dirkster99** [comment]
I have created 2 new nugets with the suggested solution (may take a minute until they appear in VS):
- version 3.1.0 targeting .Net 4.0 only and
- version 1.3.1-alpha  preview targeting .Net 4.0  and NetCore 3.0

Rebuild/Release is a bit of a pain right now 👎 but NetCore 3.0 is hopefully ready for WPF soon 👍
