### ISSUE TITLE
Solution not opening

### ISSUE THREAD

**Issue by lutecki** [Dirkster99/InplaceEditBoxLib#9]
Just tried the master branch and I cannot open the solution:

![obraz](https://user-images.githubusercontent.com/31219810/70186550-6b820f00-16ec-11ea-9a38-f5fd583f1004.png)

~~~\InplaceEditBoxLib-master\source\Services\ExplorerLib\ExplorerLib.csproj : error  : Project file is incomplete. Expected imports are missing.

~~~\InplaceEditBoxLib-master\source\Services\ServiceLocator\ServiceLocator.csproj : error  : Project file is incomplete. Expected imports are missing.

~~~\InplaceEditBoxLib-master\source\Solution\SolutionLib\SolutionLib.csproj : error  : Project file is incomplete. Expected imports are missing.

~~~\InplaceEditBoxLib-master\source\Solution\SolutionLibModels\SolutionLibModels.csproj : error  : Project file is incomplete. Expected imports are missing.

~~~\InplaceEditBoxLib-master\source\InplaceEditBoxLib\InplaceEditBoxLib.csproj : error  : Project file is incomplete. Expected imports are missing.

I'm using VS2017 Community
Regards.

**Comment by Dirkster99** [comment]
This solution support multitargeting .Net4 and NetCore3 which means that you will need at least VS 2019 Community Edition - you could get this to work in VS 2017 Community Edition but you would have to rebuild all projects mannually in VS 2017 Community Edition - but thats a lot of manual work and requires you to understand the VS 2019 project structure (its easier in many ways but different enough to make you wonder [if you have not seen this before](https://github.com/Dirkster99/InplaceEditBoxLib/blob/master/source/InplaceEditBoxLib/InplaceEditBoxLib.csproj)...).

Please let me know if your problem persists in VS 2019 I'll be happy to look into it.
